<?php
$products = [
    1 => ['name' => 'SJSU Gameday Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-blue-san-jose-state-spartans-lightweight-basketball-jersey_pi4726000_ff_4726175-e6a6ade88b13a9e08009_full.jpg?_hv=2'],
    2 => ['name' => 'SJSU Gameday Royal Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-number-1-royal-san-jose-state-spartans-lightweight-basketball-jersey_ss5_p-200939480+u-r981abcxbwg6dbzqihcy+v-8zufjmlgvxfalrxufoig.png?_hv=2&w=400'],
    3 => ['name' => 'Custom SJSU Gameday Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/unisex-gameday-greats-white-san-jose-state-spartans-nil-pick-a-player-lightweight-soccer-jersey_ss5_p-200728453+u-1t2mkqqrxsanfey03el6+v-q0mdwdqeaixgiv93dmqr.jpg?_hv=2&w=400'],
    4 => ['name' => 'SJSU Gameday Greats Blue Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-blue-san-jose-state-spartans-lightweight-basketball-jersey_pi4726000_ff_4726175-e6a6ade88b13a9e08009_full.jpg?_hv=2&w=400'],
    5 => ['name' => 'SJSU Gameday Greats White Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-number-1-white-san-jose-state-spartans-lightweight-basketball-jersey_ss5_p-200939478+u-xvp0epcklssnbrypc8p5+v-gsbwtolktlbsbbcyvn3z.png?_hv=2&w=400'],
    6 => ['name' => 'SJSU Gameday Greats Pink Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/unisex-gameday-greats-number-1-pink-san-jose-state-spartans-lightweight-basketball-jersey_ss5_p-201141949+u-9lvr3hj9bzraapkebwzh+v-2i2m0oyavdyulpk1wg9l.jpg?_hv=2&w=400'],
    7 => ['name' => 'SJSU Gameday Greats Royal Jersey', 'desc' => 'Lightweight basketball jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/unisex-gameday-greats-number-1-royal-san-jose-state-spartans-lightweight-basketball-fashion-jersey_ss5_p-202342842+u-plrdjkyflkxu3dsrfxm5+v-jgl8iwwgyt83dc62sb2i.jpg?_hv=2&w=400'],
    8 => ['name' => 'SJSU Gameday Black Jersey', 'desc' => 'Lightweight football jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-number-1-black-san-jose-state-spartans-football-jersey_ss5_p-200588995+u-zosahcmxsdhfkgnscoik+v-igkbrgvtyt59mdn9wcor.jpg?_hv=2&w=400'],
    9 => ['name' => 'SJSU Gameday Royal Spartan Jersey', 'desc' => 'Lightweight football jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/gameday-greats-number-1-royal-san-jose-state-spartans-lightweight-collegiate-football-fashion-jersey_ss5_p-202219860+u-psn6ewsmdhlwc7vm8zyk+v-acc2twbxsocxweensiwu.jpg?_hv=2&w=400'],
    10 => ['name' => 'SJSU Gameday White Jersey', 'desc' => 'Lightweight football jersey.', 'img' => 'https://images.footballfanatics.com/san-jose-state-spartans/mens-gameday-greats-number-1-white-san-jose-state-spartans-football-jersey_ss5_p-200588997+u-gaxepd6bkrlch3jmugnm+v-iwpwxemk6g9uwtokbwjf.jpg?_hv=2&w=400'],
];
?>